export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_GET_ALL = 'USER_GET_ALL'
export const USER_UPDATE_USERROLE = 'USER_UPDATE_USERROLE'

export const LINKS_INIT = 'LINKS_INIT'
export const LINKS_ADD = 'LINKS_ADD'
export const LINKS_DELETE = 'LINKS_DELETE'
export const LINKS_UPDATE = 'LINKS_UPDATE'

export const COMMENTS_LINK_INIT = 'COMMENTS_INIT'
export const COMMENTS_LINK_ADD = 'COMMENTS_ADD' 
export const COMMENTS_LINK_DELETE = 'COMMENTS_LINK_DELETE'

export const CATEGORY_ADD = 'CATEGORY_ADD'
export const CATEGORY_INIT = 'CATEGORY_INIT'